### ISSUE TITLE
RuntimeError(f"Directory '{directory}' does not exist") error

### ISSUE THREAD

**Issue by hakanuzum** [denisov-vlad/simple-snowplow#17]
Hi Vlad, 
When I try to test with local installation, I get the error in the image.
It seems like I will probably get a similar error when I try other methods.
Test environment windows wsl2 ubuntu

![image](https://github.com/denisov-vlad/simple-snowplow/assets/16476982/95833033-2c49-4b64-9930-5a879d110d8e)

**Comment by denisov-vlad** [comment]
Hi @hakanuzum 

Thanks for the reports. I've fixed this error.
